# Setup
title:        Joon's blog
tagline:      문준의 블로그입니다
baseurl:      "https://nrbam123.github.io/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Joon's blog
  url:        https://nrbam123/nrbam123.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
