# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Joon's blog
  url:        https://nrbam123/nrbam123.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
